/* =========================================================================
   main.js - Interactive Documentary Timeline & Engine
   ========================================================================= */

document.addEventListener('DOMContentLoaded', () => {

    // Document Timeline Data: 300 Seconds (5 Minutes Total)
    const documentaryTimeline = [
        // --- CHAPTER 1: EXTRACTION & THE VALUE PARADOX (00:00 - 01:00) ---
        {
            time: 0,
            chapter: "CHAPTER 1 // EXTRACTION & THE VALUE PARADOX",
            title: "GHOST IN THE MACHINE",
            subtitle: "How Generative AI Produces, Consumes, and Redistributes Value",
            text: "Every click, upload, and brushstroke in modern digital life fuels an unprecedented extraction engine. But who truly owns the value generated by our collective digital existence?",
            visual: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1920&auto=format&fit=crop",
            statNum: "$1.3T",
            statText: "Projected economic impact of Generative AI on media and tech sectors by 2032.",
            showTitle: true
        },
        {
            time: 15,
            chapter: "CHAPTER 1 // EXTRACTION & THE VALUE PARADOX",
            title: "",
            subtitle: "",
            text: "In the digital media economy, human creativity was historically valued as an individual artisan skill. Today, digital life converts human output into raw algorithmic inputs.",
            visual: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=1920&auto=format&fit=crop",
            statNum: "70%",
            statText: "Of creative professionals report structural shifts in project compensation due to AI.",
            showTitle: false
        },
        {
            time: 35,
            chapter: "CHAPTER 1 // EXTRACTION & THE VALUE PARADOX",
            title: "",
            subtitle: "",
            text: "Platform capitalism thrives on this asymmetry: users and artists produce cultural rich media, while platform monopolies extract and enclose its economic surplus.",
            visual: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=1920&auto=format&fit=crop",
            statNum: "3 Platforms",
            statText: "Consolidate the majority of foundational Generative AI visual and textual foundation models.",
            showTitle: false
        },

        // --- CHAPTER 2: THE SCRAPING ENGINE & UNCONSENTED LABOR (01:00 - 02:00) ---
        {
            time: 60,
            chapter: "CHAPTER 2 // SCRAPING WITHOUT CONSENT",
            title: "ENCLOSING THE COMMONS",
            subtitle: "Turning Human Culture into Raw Training Data",
            text: "Generative AI systems—from ChatGPT to Gemini and Sora—do not create from nothingness. They rely on billions of images, texts, and soundscapes scraped without consent.",
            visual: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=1920&auto=format&fit=crop",
            statNum: "5.8B+",
            statText: "Scraped image-text pairs in datasets like LAION-5B, harvested without creator royalty.",
            showTitle: true
        },
        {
            time: 80,
            chapter: "CHAPTER 2 // SCRAPING WITHOUT CONSENT",
            title: "",
            subtitle: "",
            text: "Artists spend decades refining individual styles, tone, and visual language. AI models digest these portfolios in seconds, stripping away attribution, context, and consent.",
            visual: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=1920&auto=format&fit=crop",
            statNum: "0%",
            statText: "Direct royalty payout mandated to individual creators by major commercial foundation models.",
            showTitle: false
        },
        {
            time: 100,
            chapter: "CHAPTER 2 // SCRAPING WITHOUT CONSENT",
            title: "",
            subtitle: "",
            text: "By transforming artistic legacy into static weight matrices, technology firms centralize economic power, transferring wealth from human creators to server infrastructure owners.",
            visual: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1920&auto=format&fit=crop",
            statNum: "$100B+",
            statText: "Capital expenditure invested in data center compute to train foundational AI architectures.",
            showTitle: false
        },

        // --- CHAPTER 3: AUTOMATION & PROFESSIONAL DISRUPTION (02:00 - 03:00) ---
        {
            time: 120,
            chapter: "CHAPTER 3 // AUTOMATION & DISRUPTION",
            title: "DEVALUING THE ARTISAN",
            subtitle: "Task Automation across Writing, Design, and Video Production",
            text: "AI tools now automate copywriting, illustration, music synthesis, and cinematic editing. Tasks that took weeks are executed in seconds, reshaping professional creative labor.",
            visual: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?q=80&w=1920&auto=format&fit=crop",
            statNum: "-35%",
            statText: "Decline in freelance job postings for entry-level copywriting and basic graphic design.",
            showTitle: true
        },
        {
            time: 145,
            chapter: "CHAPTER 3 // AUTOMATION & DISRUPTION",
            title: "",
            subtitle: "",
            text: "Rather than removing drudgery, automation often targets the core expressive acts of human talent, converting skilled artisans into prompt operators and fast reviewers.",
            visual: "https://images.unsplash.com/photo-1542744094-3a3121699563?q=80&w=1920&auto=format&fit=crop",
            statNum: "3.2x",
            statText: "Speedup demanded in client turnaround times, driving intense productivity pressure on designers.",
            showTitle: false
        },

        // --- CHAPTER 4: GHOST LABOR & GLOBAL INEQUALITIES (03:00 - 04:00) ---
        {
            time: 180,
            chapter: "CHAPTER 4 // GHOST LABOR IN THE GLOBAL SOUTH",
            title: "THE HIDDEN WORKFORCE",
            subtitle: "Data Labeling, Moderation, and Invisible Human Exploitation",
            text: "Behind the illusion of seamless artificial intelligence lies an army of invisible human labor: data annotators, RLHF reviewers, and content moderators.",
            visual: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=1920&auto=format&fit=crop",
            statNum: "< $2/hr",
            statText: "Average wages paid to data annotation laborers in parts of Kenya, the Philippines, and India.",
            showTitle: true
        },
        {
            time: 210,
            chapter: "CHAPTER 4 // GHOST LABOR IN THE GLOBAL SOUTH",
            title: "",
            subtitle: "",
            text: "Contracted out to workers in the Global South, these precarious roles demand reviewing disturbing imagery and fine-tuning outputs under severe quota regimes.",
            visual: "https://images.unsplash.com/photo-1531482615713-2afd69097998?q=80&w=1920&auto=format&fit=crop",
            statNum: "80%",
            statText: "Of raw AI training pipelines rely on human-in-the-loop manual classification and scrubbing.",
            showTitle: false
        },

        // --- CHAPTER 5: SYNTHESIS & RESTRUCTURING CULTURAL PRODUCTION (04:00 - 05:00) ---
        {
            time: 240,
            chapter: "CHAPTER 5 // RESTRUCTURING CULTURAL PRODUCTION",
            title: "DEMOCRATIZATION OR HIERARCHY?",
            subtitle: "Reclaiming Agency in the Era of Algorithmic Power",
            text: "Generative AI introduces dual dynamics: it lowers technical barriers for amateur creation while reinforcing hyper-centralized ownership of digital infrastructure.",
            visual: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=1920&auto=format&fit=crop",
            statNum: "2026",
            statText: "A decisive decade for establishing copyright precedent, collective bargaining, and AI consent frameworks.",
            showTitle: true
        },
        {
            time: 270,
            chapter: "CHAPTER 5 // RESTRUCTURING CULTURAL PRODUCTION",
            title: "",
            subtitle: "",
            text: "The future of creative media depends on ethical governance: establishing collective bargaining, transparent data provenance, and fair compensation models for human genius.",
            visual: "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1920&auto=format&fit=crop",
            statNum: "HUMAN + AI",
            statText: "Demanding transparency, human rights in labor, and economic value redistribution.",
            showTitle: false
        }
    ];

    // State Variables
    let currentTime = 0;
    let totalDuration = 300; // 5 Minutes
    let isPlaying = false;
    let timerInterval = null;
    let currentCueIndex = -1;

    // DOM Elements
    const playBtn = document.getElementById('playBtn');
    const restartBtn = document.getElementById('restartBtn');
    const bgAudio = document.getElementById('bgAudio');
    const bgVisual = document.getElementById('bgVisual');
    const kenBurnsWrapper = document.getElementById('kenBurnsWrapper');
    const chapterBadge = document.getElementById('chapterBadge');
    const titleCard = document.getElementById('titleCard');
    const mainTitle = document.getElementById('mainTitle');
    const subTitle = document.getElementById('subTitle');
    const narrativeText = document.getElementById('narrativeText');
    const statCallout = document.getElementById('statCallout');
    const statNumber = document.getElementById('statNumber');
    const statLabel = document.getElementById('statLabel');
    const timelineProgress = document.getElementById('timelineProgress');
    const timelineContainer = document.getElementById('timelineContainer');
    const currentTimeElem = document.getElementById('currentTime');
    const visualizer = document.getElementById('visualizer');
    const chapBtns = document.querySelectorAll('.chap-btn');

    // Format Seconds to MM:SS
    function formatTime(seconds) {
        const mins = Math.floor(seconds / 60);
        const secs = Math.floor(seconds % 60);
        return `${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
    }

    // Update Documentary Viewport based on current time
    function renderFrame(time) {
        currentTimeElem.textContent = formatTime(time);
        timelineProgress.style.width = `${(time / totalDuration) * 100}%`;

        // Find appropriate timeline cue
        let cueIndex = documentaryTimeline.length - 1;
        for (let i = 0; i < documentaryTimeline.length; i++) {
            if (time < documentaryTimeline[i].time) {
                cueIndex = i - 1;
                break;
            }
        }
        if (cueIndex < 0) cueIndex = 0;

        // Apply state updates if cue changed
        if (cueIndex !== currentCueIndex) {
            currentCueIndex = cueIndex;
            const cue = documentaryTimeline[cueIndex];

            // Update Text
            chapterBadge.textContent = cue.chapter;
            narrativeText.textContent = cue.text;

            // Handle Title Overlay
            if (cue.showTitle) {
                mainTitle.textContent = cue.title;
                subTitle.textContent = cue.subtitle;
                titleCard.style.opacity = '1';
                titleCard.style.transform = 'translateY(0)';
            } else {
                titleCard.style.opacity = '0';
                titleCard.style.transform = 'translateY(-20px)';
            }

            // Handle Visuals & Ken Burns Toggle
            bgVisual.src = cue.visual;
            kenBurnsWrapper.classList.toggle('zoom-in', cueIndex % 2 === 0);
            kenBurnsWrapper.classList.toggle('pan-right', cueIndex % 2 !== 0);

            // Handle Stat Callout
            if (cue.statNum) {
                statNumber.textContent = cue.statNum;
                statLabel.textContent = cue.statText;
                statCallout.classList.add('active');
            } else {
                statCallout.classList.remove('active');
            }

            // Highlight Chapter Button
            chapBtns.forEach(btn => {
                const btnTime = parseInt(btn.getAttribute('data-time'));
                btn.classList.toggle('active', time >= btnTime && time < btnTime + 60);
            });
        }
    }

    // Play/Pause Engine
    function togglePlay() {
        if (isPlaying) {
            pauseDoc();
        } else {
            playDoc();
        }
    }

    function playDoc() {
        isPlaying = true;
        playBtn.textContent = "PAUSE";
        visualizer.classList.add('playing');
        bgAudio.play().catch(() => console.log("Audio playback user gesture required"));

        timerInterval = setInterval(() => {
            currentTime++;
            if (currentTime >= totalDuration) {
                currentTime = totalDuration;
                pauseDoc();
            }
            renderFrame(currentTime);
        }, 1000);
    }

    function pauseDoc() {
        isPlaying = false;
        playBtn.textContent = "PLAY";
        visualizer.classList.remove('playing');
        bgAudio.pause();
        clearInterval(timerInterval);
    }

    function seekTo(time) {
        currentTime = time;
        renderFrame(currentTime);
    }

    // Event Listeners
    playBtn.addEventListener('click', togglePlay);

    restartBtn.addEventListener('click', () => {
        pauseDoc();
        seekTo(0);
        playDoc();
    });

    timelineContainer.addEventListener('click', (e) => {
        const rect = timelineContainer.getBoundingClientRect();
        const clickPos = (e.clientX - rect.left) / rect.width;
        seekTo(Math.floor(clickPos * totalDuration));
    });

    chapBtns.forEach(btn => {
        btn.addEventListener('click', () => {
            const targetTime = parseInt(btn.getAttribute('data-time'));
            seekTo(targetTime);
            if (!isPlaying) playDoc();
        });
    });

    // Initialize First Frame
    renderFrame(0);
});
